---
- name: Configure nginx web server
  hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: Install nginx server
    yum:
      name:
        - nginx
      state: latest
  - name: Start nginx server
    service:
      name: nginx
      state: started
      